POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Video 01",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

GET http://localhost:3333/videos?search=vid


###


PUT http://localhost:3333/videos/60dc5f5c-5bab-4dfd-8153-3e961cfec0ff
content-type: application/json

{
  "title": "Video 02",
  "description": "Esse é o primeiro vídeo",
  "duration": 180
}

###

DELETE http://localhost:3333/videos/26bf0c4b-beab-430d-be7f-d7beb616db29